### PR TITLE
PR for code review

### PR DESCRIPTION
**Pull request by dili021**
This project was built using Javascript considering the requirements as below,

Following the lesson about Factory Functions and The Module Pattern so the main goal is to put into practice those concepts along with the main concepts of Object-Oriented Programming. Particularly, classes/objects and how to access their methods and attributes.
Do not commit console.log to your repo. It’s ugly, it kills performance and it can make confidential data be visible in the browser tools.
-Keep the number of changes/updates to the DOM as low as possible, they are very expensive for the browser.
-Keep the application logic separated from DOM manipulation tasks.
-Keep all the styling logic in CSS files.
-If you use node modules - .lock files should be in the repository to avoid problems with future versions of the dependencies.
-If you use ES6 - use object destructuring to get the values from an object. This way you can avoid repeating a lot of code.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required.
Great job on this project.
There is a bug when the last remaining position move leads to a win. The game results into a draw instead of a win. Check this :point_down: 
Screenshot from 2020-08-28 20-27-59

**Please fix the bug and submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

**Review by uryelah — CHANGES_REQUESTED** [review]
Hi **Stefan Dili & Rajkumar Das Das**, I'm Sarah your reviewer for this PR 👩‍🚀 

Hey guys, it seems that some of the refactoring done while separating the code in different files broke the code a bit. It's ok if you do it all at the same file since this is before the webpack lesson.
Check the points below for the specific error I got.

# Required Changes 🏗️ 🐛 💡

- [ ] Sadly I can not run the game on either Chrome or Firefox.
I get the errors below. Since this project is before webpack it's ok to keep it all in the same file, you can use comments to divide the dom related area from the logic related one.
firefox _n_chrome_erors
it's ok to note use file modules right now.

- [ ] Why do you have a package-lock file? Usually, when we use npm packages in a project you have a package.json file that will create the node_modules and package-lock, if it's not there. Is there a reason you have it there?

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by dili021** [comment]
@uryelah Please note that between your and Simon's review, the only thing that changed in the code is the logic error for the draw/win condition, and it worked on his side, as well as mine and Raj's. Can the problem possibly be on your side? Looking around SO posts, I see this is is possible the script is not defined as a module in the html file, which it has been from the beginning on our side. we had tons of errors through this project, but none of them were CORS related.

As for the package-lock, it was we didn't add it. It was generated when we installed eslint and stylelint, and we haven't modified anything.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right this time :clap: The project has been approved. Congratulations :boom:
### Merge and submit the project. Good luck with the next one.
- Happy Hacking

### Optional
- Remove the comments
- Organize your files into modules, this is easy to maintain and read

**Pull request merged**
